<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="vasanthvasu" name="com.leafBot.testcases.TC002_LoginForFailure" tests="5" failures="0" timestamp="2021-06-12T12:30:05 GMT+05:30" time="0.000" errors="1">
  <testcase name="createLeaf" time="0.000" classname="com.leafBot.testcases.TC002_LoginForFailure">
    <skipped/>
  </testcase> <!-- createLeaf -->
  <system-out/>
  <testcase name="report" time="0.000" classname="com.leafBot.testcases.TC002_LoginForFailure">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.leafBot.testng.utils.Reporter.report(Reporter.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner$$Lambda$55/24555242.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1234)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- report -->
  <system-out/>
  <testcase name="createLeaf" time="0.000" classname="com.leafBot.testcases.TC002_LoginForFailure">
    <skipped/>
  </testcase> <!-- createLeaf -->
  <system-out/>
  <testcase name="createLeaf" time="0.000" classname="com.leafBot.testcases.TC002_LoginForFailure">
    <skipped/>
  </testcase> <!-- createLeaf -->
  <system-out/>
  <testcase name="createLeaf" time="0.000" classname="com.leafBot.testcases.TC002_LoginForFailure">
    <skipped/>
  </testcase> <!-- createLeaf -->
  <system-out/>
</testsuite> <!-- com.leafBot.testcases.TC002_LoginForFailure -->
